# Generated by Django 6.0.4 on 2026-05-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0025_alter_recurring_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(unique=True)),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celery', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'indexes': [models.Index(fields=['start'], name='scheduler_t_start_8cc05c_idx')],
            },
        ),
    ]
