# Generated by Django 6.0.4 on 2026-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(unique=True)),
                ('start', models.DateTimeField()),
                ('ending', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RC', 'Received'), ('PR', 'Processing'), ('RN', 'Running'), ('CN', 'Completed'), ('ERR', 'Error')])),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-start'],
            },
        ),
    ]
