# Generated by Django 6.0.4 on 2026-05-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
    ]
