# Generated by Django 6.0.4 on 2026-05-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celery', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='celerytask',
            index=models.Index(fields=['start'], name='scheduler_c_start_e7c65f_idx'),
        ),
    ]
