# Generated by Django 6.0.4 on 2026-05-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('RC', 'Recieved'), ('RV', 'Revoked'), ('CM', 'Completed'), ('RN', 'Running'), ('ERR', 'Error')], default='RC'),
            preserve_default=False,
        ),
    ]
