# Generated by Django 6.0.4 on 2026-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(choices=[('RC', 'Received'), ('PR', 'Processing'), ('RN', 'Running'), ('CN', 'Completed'), ('ERR', 'Error')], default='RC'),
        ),
    ]
