# Generated by Django 6.0.4 on 2026-05-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_task_ending_task_status'),
        ('tasks', '0025_alter_recurring_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(unique=True)),
                ('start', models.DateTimeField()),
                ('ending', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RC', 'Recieved'), ('PR', 'Processing'), ('CN', 'Completed'), ('ERR', 'Error')])),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-start'],
            },
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='scheduler_t_start_8cc05c_idx',
        ),
        migrations.AddField(
            model_name='celerytask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celery', to='tasks.task'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddIndex(
            model_name='celerytask',
            index=models.Index(fields=['start'], name='scheduler_c_start_e7c65f_idx'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
