# Generated by Django 6.0.4 on 2026-05-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_celerytask_remove_task_scheduler_t_start_8cc05c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(choices=[('RC', 'Recieved'), ('PR', 'Processing'), ('RN', 'Running'), ('CN', 'Completed'), ('ERR', 'Error')]),
        ),
    ]
