# Generated by Django 6.0.4 on 2026-05-11 17:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started', models.BooleanField(blank=True, default=False)),
                ('expired', models.BooleanField(blank=True, default=False)),
                ('completed', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField()),
                ('duration_time', models.DurationField(blank=True, editable=False)),
                ('interval', models.DurationField(default=datetime.timedelta(days=7))),
            ],
        ),
        migrations.CreateModel(
            name='RecurringState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_time', models.DateTimeField(blank=True)),
                ('ends_at', models.DateTimeField(blank=True)),
                ('recurring', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='tasks.recurring')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.recurringstate')),
            ],
            options={
                'ordering': ['-ended_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='tasks_task_created_177597_idx'), models.Index(fields=['user'], name='tasks_task_user_id_0b1849_idx'), models.Index(fields=['content_type', 'object_id'], name='tasks_task_content_2bbe5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_content_type_object_id')],
            },
        ),
    ]
