# Generated by Django 6.0.4 on 2026-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringstatehistory',
            name='task_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringstatehistory',
            name='task_name',
            field=models.CharField(default='No name'),
            preserve_default=False,
        ),
    ]
