# Generated by Django 6.0.4 on 2026-04-19 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_task_type_onetimetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimetask',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_time', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
