# Generated by Django 6.0.4 on 2026-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_recurringstatehistory_task_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='onetime',
            index=models.Index(fields=['started', 'expired'], name='tasks_oneti_started_c34eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='onetime',
            index=models.Index(fields=['expired', 'completed'], name='tasks_oneti_expired_51dc6a_idx'),
        ),
    ]
