# Generated by Django 6.0.4 on 2026-04-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_onetimetask_task_alter_task_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OneTimeTask',
            new_name='OneTime',
        ),
    ]
