# Generated by Django 6.0.4 on 2026-05-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_onetime_tasks_oneti_started_c34eb8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringstatehistory',
            name='task_id',
        ),
        migrations.AddField(
            model_name='recurringstatehistory',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
            preserve_default=False,
        ),
    ]
