# Generated by Django 6.0.4 on 2026-05-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_recurringstatehistory_task_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recurringstate',
            index=models.Index(fields=['id', 'is_running'], name='tasks_recur_id_9f8932_idx'),
        ),
    ]
