# Generated by Django 6.0.4 on 2026-04-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_onetimetask_onetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetime',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onetime', to='tasks.task'),
        ),
    ]
