# Generated by Django 6.0.4 on 2026-04-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0005_alter_onetime_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetime',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='object_id',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onetime',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
