# Generated by Django 6.0.4 on 2026-05-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_recurringstate_tasks_recur_id_9f8932_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recurringstatehistory',
            index=models.Index(fields=['ended_at'], name='tasks_recur_ended_a_92c1e0_idx'),
        ),
    ]
