# Generated by Django 6.0.4 on 2026-04-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_onetime_task_task_content_type_task_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='object_id',
        ),
        migrations.AddField(
            model_name='onetime',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onetime', to='tasks.task'),
        ),
    ]
