# Generated by Django 6.0.4 on 2026-05-20 15:40

import tasks.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_recurringstatehistory_tasks_recur_ended_a_92c1e0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringstatehistory',
            name='relative_id',
            field=tasks.fields.TaskRelativeIdField(default=0),
            preserve_default=False,
        ),
    ]
