# Generated by Django 6.0.4 on 2026-04-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0007_remove_task_content_type_remove_task_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetime',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': 'onetime'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='object_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
