# Generated by Django 6.0.4 on 2026-05-20 15:46

import tasks.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_recurringstatehistory_relative_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='relative_id',
            field=tasks.fields.TaskRelativeIdField(unique=True),
        ),
    ]
