# Generated by Django 6.0.4 on 2026-05-20 16:09

import tasks.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_recurringstatehistory_relative_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='relative_id',
            field=tasks.fields.TaskRelativeIdField(),
        ),
        migrations.AddConstraint(
            model_name='recurringstatehistory',
            constraint=models.UniqueConstraint(fields=('task_id', 'relative_id'), name='unique_task_id_relative_id'),
        ),
    ]
