# Generated by Django 6.0.4 on 2026-04-30 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_recurring_task_tasks_task_content_2bbe5a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='duration_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
