# Generated by Django 6.0.4 on 2026-04-30 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_recurring_duration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_time', models.DateTimeField()),
                ('recurring', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='tasks.recurring')),
            ],
        ),
    ]
