# Generated by Django 6.0.4 on 2026-05-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_recurringstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringstate',
            name='until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
