# Generated by Django 6.0.4 on 2026-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_recurringstate_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringstate',
            old_name='active',
            new_name='is_running',
        ),
        migrations.RemoveField(
            model_name='recurringstate',
            name='until',
        ),
        migrations.AlterField(
            model_name='recurring',
            name='duration_time',
            field=models.DurationField(blank=True, editable=False),
        ),
    ]
