# Generated by Django 6.0.4 on 2026-05-02 16:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0015_rename_active_recurringstate_is_running_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_user_id_f226ed_idx',
        ),
        migrations.AddField(
            model_name='onetime',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringstate',
            name='ends_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 2, 16, 44, 2, 50269, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurringstate',
            name='next_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='tasks_task_user_id_0b1849_idx'),
        ),
        migrations.AddField(
            model_name='recurringstatehistory',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completes', to='tasks.recurringstate'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
