# Generated by Django 6.0.4 on 2026-05-03 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_recurringstatehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringstate',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='ends_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='started_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='state',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='completes', to='tasks.recurringstate'),
        ),
    ]
