# Generated by Django 6.0.4 on 2026-05-04 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_recurringstate_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
