# Generated by Django 6.0.4 on 2026-05-05 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_recurring_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringstatehistory',
            options={'ordering': ['-ends_at']},
        ),
        migrations.AlterField(
            model_name='recurringstate',
            name='recurring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='state', to='tasks.recurring'),
        ),
    ]
