# Generated by Django 6.0.4 on 2026-05-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_recurringstatehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringstatehistory',
            options={'ordering': ['-ended_at']},
        ),
        migrations.RenameField(
            model_name='recurringstatehistory',
            old_name='ends_at',
            new_name='ended_at',
        ),
    ]
