# Generated by Django 6.0.4 on 2026-05-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_recurringstatehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recurringstatehistory',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.recurringstate'),
        ),
    ]
