# Generated by Django 6.0.4 on 2026-05-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_recurringstatehistory_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetime',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringstate',
            name='recurring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='tasks.recurring'),
        ),
    ]
