# Generated by Django 6.0.4 on 2026-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_onetime_starts_at_alter_recurringstate_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetime',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='onetime',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='onetime',
            name='expired',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
