# Generated by Django 6.0.4 on 2026-05-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_onetime_active_alter_onetime_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetime',
            old_name='active',
            new_name='started',
        ),
    ]
