# Generated by Django 6.0.4 on 2026-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_rename_active_onetime_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
