# Generated by Django 6.0.4 on 2026-05-09 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_alter_recurring_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetime',
            name='starts_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 9, 15, 31, 59, 649574, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
