services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: qmayker
      POSTGRES_PASSWORD: 101210
  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    
  celery:
    build: .
    command: celery -A todo worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
  flower:
    build: .
    command: celery -A todo flower --port=5555 --adress=0.0.0.0
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - celery

volumes:
  redisdata: