services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: qmayker
      POSTGRES_PASSWORD: 101210
  redis:
    image: redis
  celery:
    build: .
    command: celery -A todo worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
  beat:
    build: .
    command: celery -A todo beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    